// ============================================================
// PRODUCTS DATA — Edit this file to add / change products
// After editing, commit + push to GitHub → live for everyone
// ============================================================
//
// Format (no price — button goes straight to Amazon):
// {
//   "id": "B095T14D4S",
//   "title": "...",
//   "slug": "product-url-slug",
//   "description": "...",
//   "category": "electronics",
//   "brand": "Raycon",
//   "asin": "B095T14D4S",
//   "image": "https://m.media-amazon.com/images/I/....jpg",
//   "amazonUrl": "https://www.amazon.com/dp/B095T14D4S?tag=sheroztariq-20",
//   "buttonText": "Check Price",
//   "rating": 4.2,
//   "reviewCount": 30859,
//   "badge": "Amazon's Choice",
//   "featured": true
// }

const PRODUCTS = [
  {
    "id": "sony-wh-1000xm5",
    "title": "Sony WH-1000XM5 Wireless Noise-Canceling Headphones",
    "slug": "sony-wh-1000xm5",
    "description": "Industry-leading noise canceling, 30-hour battery, and a lighter sculpted fit. The XM5 is the commute, flight, and deep-work default.",
    "category": "electronics",
    "brand": "Sony",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Sony+WH-1000XM5&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.8,
    "reviewCount": 21403,
    "badge": "Flash Deal",
    "featured": true
  },
  {
    "id": "airpods-pro-2",
    "title": "Apple AirPods Pro (2nd Generation) with USB-C",
    "slug": "airpods-pro-2",
    "description": "Adaptive Audio, conversation awareness, and a USB-C case. Spatial sound that actually earns the hype.",
    "category": "electronics",
    "brand": "Apple",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Apple+AirPods+Pro+2+USB-C&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.7,
    "reviewCount": 54012,
    "badge": "Best Seller",
    "featured": true
  },
  {
    "id": "kindle-paperwhite-16",
    "title": "Kindle Paperwhite (16 GB) — Glare-Free Display",
    "slug": "kindle-paperwhite-16",
    "description": "A 6.8-inch glare-free screen, weeks of battery, and waterproofing for the bath, beach, or delayed flight.",
    "category": "electronics",
    "brand": "Amazon",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Kindle+Paperwhite+16GB&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.8,
    "reviewCount": 89011,
    "badge": null,
    "featured": true
  },
  {
    "id": "mx-master-3s",
    "title": "Logitech MX Master 3S Performance Mouse",
    "slug": "mx-master-3s",
    "description": "Quiet clicks, 8K DPI MagSpeed scrolling, and multi-device flow for people who live in Figma and terminals.",
    "category": "electronics",
    "brand": "Logitech",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Logitech+MX+Master+3S&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.7,
    "reviewCount": 18220,
    "badge": "Editor's Pick",
    "featured": false
  },
  {
    "id": "soundcore-motion-plus",
    "title": "Anker Soundcore Motion+ Portable Bluetooth Speaker",
    "slug": "soundcore-motion-plus",
    "description": "Hi-res audio, 12 hours of play, and a surprisingly wide soundstage for a speaker that fits in a weekender.",
    "category": "electronics",
    "brand": "Anker",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Anker+Soundcore+Motion+Plus&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.6,
    "reviewCount": 9340,
    "badge": "Flash Deal",
    "featured": false
  },
  {
    "id": "samsung-990-evo-2tb",
    "title": "Samsung 990 EVO Plus 2TB NVMe SSD",
    "slug": "samsung-990-evo-2tb",
    "description": "PCIe 4.0 speed for libraries, 4K timelines, and games that refuse to stay small. Reliable, quiet, fast.",
    "category": "electronics",
    "brand": "Samsung",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Samsung+990+EVO+Plus+2TB&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.7,
    "reviewCount": 6120,
    "badge": null,
    "featured": false
  },
  {
    "id": "fujifilm-x100vi",
    "title": "Fujifilm X100VI Digital Camera",
    "slug": "fujifilm-x100vi",
    "description": "The street photographer's compact: 40MP, in-body stabilization, and film simulations that skip the preset pack.",
    "category": "electronics",
    "brand": "Fujifilm",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Fujifilm+X100VI&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.9,
    "reviewCount": 2104,
    "badge": "Rare Find",
    "featured": true
  },
  {
    "id": "levis-501-original",
    "title": "Levi's 501 Original Fit Jeans",
    "slug": "levis-501-original",
    "description": "The cut that defined denim. Rigid or stretch, these fade honestly and survive every season in rotation.",
    "category": "fashion",
    "brand": "Levi's",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Levi%27s+501+Original+Fit+Jeans&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.5,
    "reviewCount": 32011,
    "badge": null,
    "featured": true
  },
  {
    "id": "ultraboost-22",
    "title": "Adidas Ultraboost 22 Running Shoes",
    "slug": "ultraboost-22",
    "description": "Boost cushioning and a Primeknit upper that disappears on long days. City miles, travel days, recovery walks.",
    "category": "fashion",
    "brand": "Adidas",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Adidas+Ultraboost+22&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.6,
    "reviewCount": 14022,
    "badge": "Flash Deal",
    "featured": true
  },
  {
    "id": "rayban-aviator-classic",
    "title": "Ray-Ban Aviator Classic Gold / Green",
    "slug": "rayban-aviator-classic",
    "description": "The original teardrop. Crystal lenses, gold metal, and a silhouette that still photographs correctly.",
    "category": "fashion",
    "brand": "Ray-Ban",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1572635196237-14b3f281169d?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Ray-Ban+Aviator+Classic&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.7,
    "reviewCount": 8900,
    "badge": null,
    "featured": false
  },
  {
    "id": "tnf-nuptse-1996",
    "title": "The North Face 1996 Retro Nuptse Jacket",
    "slug": "tnf-nuptse-1996",
    "description": "700-fill down, oversized baffles, and the color-block that started a thousand lookalikes. Winter, handled.",
    "category": "fashion",
    "brand": "The North Face",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=The+North+Face+1996+Retro+Nuptse&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.8,
    "reviewCount": 5400,
    "badge": "Winter",
    "featured": false
  },
  {
    "id": "fossil-grant-chrono",
    "title": "Fossil Grant Chronograph Watch",
    "slug": "fossil-grant-chrono",
    "description": "A dress-casual chronograph with a genuine leather strap. Enough presence for a meeting, light enough for a weekend.",
    "category": "fashion",
    "brand": "Fossil",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Fossil+Grant+Chronograph&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.5,
    "reviewCount": 7600,
    "badge": null,
    "featured": true
  },
  {
    "id": "herschel-little-america",
    "title": "Herschel Little America Backpack",
    "slug": "herschel-little-america",
    "description": "A structured 25L pack with a padded 16-inch sleeve and the rolled top that still looks considered.",
    "category": "fashion",
    "brand": "Herschel",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Herschel+Little+America+Backpack&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.6,
    "reviewCount": 4300,
    "badge": null,
    "featured": false
  },
  {
    "id": "instant-pot-duo-6qt",
    "title": "Instant Pot Duo 7-in-1 Electric Pressure Cooker (6 Qt)",
    "slug": "instant-pot-duo-6qt",
    "description": "Pressure cook, slow cook, sauté, steam, and keep warm. Weeknight dal, weekend bone broth, one appliance.",
    "category": "home",
    "brand": "Instant Pot",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1584568694244-14fbdf83c267?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Instant+Pot+Duo+7-in-1+6+quart&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.7,
    "reviewCount": 120400,
    "badge": "Best Seller",
    "featured": true
  },
  {
    "id": "dyson-v8-absolute",
    "title": "Dyson V8 Absolute Cordless Vacuum",
    "slug": "dyson-v8-absolute",
    "description": "Whole-machine filtration and fade-free suction. Stairs, cars, and the rug that collects everything.",
    "category": "home",
    "brand": "Dyson",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1558317374-acc94d032f50?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Dyson+V8+Absolute&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.6,
    "reviewCount": 28900,
    "badge": "Flash Deal",
    "featured": false
  },
  {
    "id": "nespresso-vertuo-next",
    "title": "Nespresso Vertuo Next Coffee Machine",
    "slug": "nespresso-vertuo-next",
    "description": "Barcode-reading brew that spans espresso to alto. Centrifusion, not a compromise, for people who hate waiting.",
    "category": "home",
    "brand": "Nespresso",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Nespresso+Vertuo+Next&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.5,
    "reviewCount": 11200,
    "badge": null,
    "featured": true
  },
  {
    "id": "philips-hue-starter",
    "title": "Philips Hue White and Color Ambiance Starter Kit",
    "slug": "philips-hue-starter",
    "description": "Three bulbs and a bridge. Warm reading light at 7pm, cinema dim at 9, and schedules that actually stick.",
    "category": "home",
    "brand": "Philips Hue",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Philips+Hue+White+and+Color+Starter+Kit&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.6,
    "reviewCount": 19800,
    "badge": null,
    "featured": false
  },
  {
    "id": "breville-barista-express",
    "title": "Breville Barista Express Espresso Machine",
    "slug": "breville-barista-express",
    "description": "Integrated conical burr grinder, PID, and a steam wand that can texture milk without a second appliance.",
    "category": "home",
    "brand": "Breville",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1517668808823-6abb6a109c18?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Breville+Barista+Express&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.7,
    "reviewCount": 15400,
    "badge": "Premium",
    "featured": true
  },
  {
    "id": "casper-original-pillow",
    "title": "Casper Original Pillow — Standard",
    "slug": "casper-original-pillow",
    "description": "Down-alternative fill with a cooling cover. Supportive without the hotel-brick density.",
    "category": "home",
    "brand": "Casper",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1584100936595-c0654b55a2e6?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Casper+Original+Pillow&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.4,
    "reviewCount": 8900,
    "badge": null,
    "featured": false
  },
  {
    "id": "cerave-moisturizing-cream",
    "title": "CeraVe Moisturizing Cream (19 oz)",
    "slug": "cerave-moisturizing-cream",
    "description": "Ceramides, hyaluronic acid, and a texture dermatologists actually recommend. The unsung hero of most vanities.",
    "category": "beauty",
    "brand": "CeraVe",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=CeraVe+Moisturizing+Cream+19+oz&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.8,
    "reviewCount": 64011,
    "badge": "Best Seller",
    "featured": true
  },
  {
    "id": "ordinary-niacinamide",
    "title": "The Ordinary Niacinamide 10% + Zinc 1%",
    "slug": "ordinary-niacinamide",
    "description": "A high-strength vitamin B3 serum for texture and shine. Clinical, unscented, and priced like a coffee.",
    "category": "beauty",
    "brand": "The Ordinary",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=The+Ordinary+Niacinamide+10+Zinc+1&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.5,
    "reviewCount": 42000,
    "badge": null,
    "featured": false
  },
  {
    "id": "chanel-chance-eau-tendre",
    "title": "Chanel Chance Eau Tendre Eau de Parfum",
    "slug": "chanel-chance-eau-tendre",
    "description": "Jasmine, quince, and a clean musk. The kind of fragrance people ask about without knowing why.",
    "category": "beauty",
    "brand": "Chanel",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Chanel+Chance+Eau+Tendre&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.7,
    "reviewCount": 5400,
    "badge": "Premium",
    "featured": true
  },
  {
    "id": "dyson-airwrap-complete",
    "title": "Dyson Airwrap Multi-Styler Complete",
    "slug": "dyson-airwrap-complete",
    "description": "Coanda airflow that curls, shapes, and dries without extreme heat. The vanity piece that replaced three tools.",
    "category": "beauty",
    "brand": "Dyson",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1522338140262-f46f5913618a?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Dyson+Airwrap+Complete&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.6,
    "reviewCount": 9800,
    "badge": "Icon",
    "featured": false
  },
  {
    "id": "manduka-pro-mat",
    "title": "Manduka PRO Yoga Mat (71\\\")",
    "slug": "manduka-pro-mat",
    "description": "6mm of closed-cell density that doesn't peel, smell, or wander. A mat you buy once.",
    "category": "sports",
    "brand": "Manduka",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1601925260368-ae2f176501e5?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Manduka+PRO+Yoga+Mat&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.8,
    "reviewCount": 6700,
    "badge": null,
    "featured": true
  },
  {
    "id": "hydroflask-32",
    "title": "Hydro Flask 32 oz Wide Mouth Bottle",
    "slug": "hydroflask-32",
    "description": "TempShield insulation that keeps ice into the evening. Powder coat, flex cap, no-sweat sides.",
    "category": "sports",
    "brand": "Hydro Flask",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Hydro+Flask+32+oz+Wide+Mouth&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.8,
    "reviewCount": 41000,
    "badge": null,
    "featured": false
  },
  {
    "id": "bowflex-selecttech-552",
    "title": "Bowflex SelectTech 552 Adjustable Dumbbells",
    "slug": "bowflex-selecttech-552",
    "description": "5 to 52.5 pounds in a dial twist. A full rack that lives under the bench instead of along the wall.",
    "category": "sports",
    "brand": "Bowflex",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Bowflex+SelectTech+552&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.6,
    "reviewCount": 22000,
    "badge": "Home Gym",
    "featured": false
  },
  {
    "id": "atomic-habits",
    "title": "Atomic Habits by James Clear (Hardcover)",
    "slug": "atomic-habits",
    "description": "The systems book that replaced a thousand morning-routine threads. Practical, unsentimental, rereadable.",
    "category": "books",
    "brand": "Avery",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Atomic+Habits+James+Clear+hardcover&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.8,
    "reviewCount": 160000,
    "badge": "Best Seller",
    "featured": true
  },
  {
    "id": "psychology-of-money",
    "title": "The Psychology of Money by Morgan Housel",
    "slug": "psychology-of-money",
    "description": "Nineteen short stories about how people think about money — more useful than another compounding spreadsheet.",
    "category": "books",
    "brand": "Harriman House",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=The+Psychology+of+Money+Morgan+Housel&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.7,
    "reviewCount": 54000,
    "badge": null,
    "featured": false
  },
  {
    "id": "lego-orchid-10311",
    "title": "LEGO Botanical Collection — Orchid (10311)",
    "slug": "lego-orchid-10311",
    "description": "A display set that never needs watering. 608 pieces, a ceramic-look pot, and a shelf that looks finished.",
    "category": "toys",
    "brand": "LEGO",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1558060370-d644479cb6f7?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=LEGO+Botanical+Collection+Orchid+10311&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.9,
    "reviewCount": 21000,
    "badge": null,
    "featured": true
  },
  {
    "id": "switch-oled",
    "title": "Nintendo Switch OLED Model",
    "slug": "switch-oled",
    "description": "A 7-inch OLED, a wide stand, and 64GB. Docked living-room nights or a tray table on a long haul.",
    "category": "toys",
    "brand": "Nintendo",
    "asin": null,
    "image": "https://images.unsplash.com/photo-1578303512597-81e6cc15536e?auto=format&fit=crop&w=1200&q=80",
    "amazonUrl": "https://www.amazon.com/s?k=Nintendo+Switch+OLED&tag=sheroztariq-20",
    "buttonText": "Check Price",
    "rating": 4.8,
    "reviewCount": 48000,
    "badge": "Gift",
    "featured": true
  }
];

const CATEGORIES = [
  { slug: "electronics", label: "Electronics", hint: "Audio, tech, kits" },
  { slug: "fashion", label: "Fashion", hint: "Apparel & watches" },
  { slug: "home", label: "Home", hint: "Kitchen & living" },
  { slug: "beauty", label: "Beauty", hint: "Skin & fragrance" },
  { slug: "sports", label: "Sports", hint: "Train & recover" },
  { slug: "books", label: "Books", hint: "Read & learn" },
  { slug: "toys", label: "Toys", hint: "Play & build" },
];
